services:
  wordpress:
    image: ead-rio-wordpress:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysql
    environment:
      PORT: '8080'
      WORDPRESS_DB_HOST: 'mysql:3306'
      WORDPRESS_DB_NAME: 'wordpress'
      WORDPRESS_DB_USER: 'wordpress'
      WORDPRESS_DB_PASSWORD: 'wordpress_password'
      WORDPRESS_AUTH_KEY: 'abyemji8b9q8pw6zhjrcqc44egvni8ho'
      WORDPRESS_AUTH_SALT: 'kn0zg1avrlh0xwub4qryhyxx50xju3bc'
      WORDPRESS_LOGGED_IN_KEY: 'z44289hl6g1tx6yu80njlfluivdozn9b'
      WORDPRESS_LOGGED_IN_SALT: 'daxnrvy7wdoxmhmy0qp4vhqmtr4ivlyb'
      WORDPRESS_NONCE_KEY: 'p123w07i53tgxoay4lvmsqcczmo6mdtl'
      WORDPRESS_NONCE_SALT: '6zr1bbm7tm83pt52f6igaajigeewnmau'
      WORDPRESS_SECURE_AUTH_KEY: 'clbky7424g2ku9orrsd6apt2sv2p3dl8'
      WORDPRESS_SECURE_AUTH_SALT: '77ylyttrhzl63bl0jsr2w42brahonpin'
      WORDPRESS_TABLE_PREFIX: 'wp_'
      WORDPRESS_DEBUG: 'false'
      WORDPRESS_CONFIG_EXTRA: |
        define('DOMAIN_CURRENT_SITE','localhost:8080');
        define('WP_HOME','http://localhost:8080');
        define('WP_SITEURL','http://localhost:8080');
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: 'root_password'
      MYSQL_DATABASE: 'wordpress'
      MYSQL_USER: 'wordpress'
      MYSQL_PASSWORD: 'wordpress_password'
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
